dbt_retail:
  outputs:
    dev:
      account: {your_account_name}
      database: VIEWS_ORDERS
      password: {your_password}
      role: transform
      schema: DEV
      threads: 1
      type: snowflake
      user: dbt_retail
      warehouse: RETAIL
  target: dev
